export const HEAD_LOGO = '/images/office_logo.png'
export const EXAMPLE_PHOTO_PROFILE = '/images/example_photo_profile.jpg'
export const BG_LOGIN = '/images/bg_login.png'
export const LOGO_LOGIN = '/images/logo_login.png'
export const EXAMPLE_DOC = '/docs/example_doc.pdf'
export const BLANKO = '/images/blanko.png'